### ISSUE TITLE
Move runtime dependencies from devDependencies to dependencies

### ISSUE THREAD

**Issue by apupier** [designer-for-camel/camel-designer#3]
in package.json

at first sight:
https://github.com/brunoNetId/camel-designer/blob/1baf813e954c68d409eaca330406cb89d685ef16/extension.js#L3-L5

		"@types/vscode": "^1.44.0",

path and fs might be good to include too.

Otherwise, I think it will work in debugging but not with a built version

**Comment by brunoNetId** [comment]
I tested creating the 'vsix' package in and installing the extension, and all seems to work fine.

**Comment by brunoNetId** [comment]
I've added vscode as a dependency, and I have confirmed both 'fs' and 'path' are part of the Node.js core, as documented here:

- https://nodejs.dev/the-nodejs-fs-module
- https://nodejs.dev/the-nodejs-path-module
