### ISSUE TITLE
Automate publishing to VS Code Marketplace

### ISSUE THREAD

**Issue by apupier** [designer-for-camel/camel-designer#5]
benefits:
- easier to test the extension for users (our experience with Camel LSP is that before we published it, only one person tried the extension, after publishing in few days we had dozens)
- automating it avoids human error when pushing

for now I think this can be done from Travis CI. We did that at the beginning for VS Code Camel LSp, see https://github.com/camel-tooling/camel-lsp-client-vscode/commit/f20be86d593057df3b408a42823328fe31375db8#diff-354f30a63fb0907d4ad57269548329e3 (this is the part removing the publish but it gives an idea how to implement it, the reason to remove it was to publish with redhat developer official account. It requires to do the publish from a specific machine for security concerns, so not from Travis)

**Comment by brunoNetId** [comment]
@apupier I think this was done, was there anything pending?

**Comment by apupier** [comment]
seems done
